# Generated by Django 4.0.1 on 2022-01-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('price', models.IntegerField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/apartments/% Y/% m/% d/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
                'ordering': ('date_created',),
            },
        ),
    ]
