# Generated by Django 4.0.1 on 2022-01-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='price',
            field=models.IntegerField(),
        ),
    ]
